Add Array.prototype.find polyfill
PERTS/silk pull request #4
Opened 2016-12-29 23:05 UTC by taptapdan

Re https://github.com/PERTS/neptune/pull/258

2016-12-29 23:51 UTC, cmacrander requested changes

2016-12-29 23:51 UTC, cmacrander commented on js/util.js
> +         'use strict';
In theory this file should be jshintable, although I think our current grunt file doesn't include silk. Please drop the `'use strict'` b/c it's already at the top of the file, and add `/* jshint bitwise: false */` to the top of the function.

2016-12-30 01:11 UTC, taptapdan commented on js/util.js
> +         'use strict';
Made the changes

2016-12-30 03:43 UTC, cmacrander approved these changes

2016-12-30 04:35 UTC, merged